// <auto-generated />
using System;
using AmorRP.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmorRP.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AmorDbContext))]
    partial class AmorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.CategoryRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedTypeIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.CharacterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HomeWorldId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeWorldName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LodestoneId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OwnershipKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LodestoneId")
                        .IsUnique();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.DefinitionRevisionRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CreationCost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeDataVersion")
                        .HasColumnType("integer");

                    b.Property<string>("UseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupId", "DefinitionId", "Revision");

                    b.HasIndex("GroupId", "CategoryId");

                    b.ToTable("definition_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_definition_cost", "\"CreationCost\" > 0");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.DefinitionRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupId", "Id");

                    b.ToTable("item_definitions", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.GroupRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrencyIconAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("CurrencyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLetters")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPotionPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("InventoryVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NextLetters")
                        .HasColumnType("integer");

                    b.Property<int>("NextPotionPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerCharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PolicyPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId")
                        .IsUnique();

                    b.HasIndex("OwnerCharacterId");

                    b.HasIndex("Id", "CurrencyIconAssetId");

                    b.ToTable("groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_policy", "\"CurrentPotionPoints\" >= 0 AND \"CurrentLetters\" >= 0 AND \"NextPotionPoints\" >= 0 AND \"NextLetters\" >= 0");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.HoldingRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DefinitionRevision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "Id");

                    b.HasIndex("GroupId", "CategoryId");

                    b.HasIndex("GroupId", "LetterId")
                        .IsUnique();

                    b.HasIndex("GroupId", "CharacterId", "TypeId");

                    b.HasIndex("GroupId", "DefinitionId", "DefinitionRevision");

                    b.HasIndex("GroupId", "CharacterId", "DefinitionId", "DefinitionRevision")
                        .IsUnique();

                    b.ToTable("holdings", null, t =>
                        {
                            t.HasCheckConstraint("ck_holding_payload", "(\"TypeId\" = 'potion' AND \"DefinitionId\" IS NOT NULL AND \"DefinitionRevision\" IS NOT NULL AND \"LetterId\" IS NULL) OR (\"TypeId\" = 'letter' AND \"LetterId\" IS NOT NULL AND \"DefinitionId\" IS NULL AND \"DefinitionRevision\" IS NULL AND \"Quantity\" <= 1)");

                            t.HasCheckConstraint("ck_holding_quantity", "\"Quantity\" >= 0 AND \"Reserved\" >= 0 AND \"Reserved\" <= \"Quantity\"");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.InfrastructureState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.ToTable("infrastructure_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bootstrap",
                            SchemaVersion = 1
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.InvitationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitation_uses", "\"Used\" >= 0 AND \"Used\" <= \"MaxUses\"");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.LetterRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstTradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "Id");

                    b.HasIndex("AuthorCharacterId");

                    b.HasIndex("GroupId", "CategoryId");

                    b.ToTable("letters", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.LoginRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExistingCharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text");

                    b.Property<string>("HomeWorldId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeWorldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectedProviderRefresh")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedVerifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StateUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.MediaAssetRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Png")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "Id");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_bounds", "\"Width\" BETWEEN 1 AND 128 AND \"Height\" BETWEEN 1 AND 128 AND octet_length(\"Png\") <= 131072");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.MembershipRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceVersion")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("Owned")
                        .HasColumnType("bigint");

                    b.Property<long>("Reserved")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TradingRestricted")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "CharacterId");

                    b.HasIndex("CharacterId", "Status");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_balance", "\"Owned\" >= 0 AND \"Reserved\" >= 0 AND \"Reserved\" <= \"Owned\"");

                            t.HasCheckConstraint("ck_membership_status", "\"Status\" IN ('active', 'dormant', 'blocked')");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.OperationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorCharacterId")
                        .HasColumnType("uuid");

                    b.Property<long?>("AfterBalance")
                        .HasColumnType("bigint");

                    b.Property<long?>("BeforeBalance")
                        .HasColumnType("bigint");

                    b.Property<long?>("Delta")
                        .HasColumnType("bigint");

                    b.Property<string>("ETag")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.HasIndex("GroupId", "OccurredAt", "Id");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.OwnershipRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCharacterId");

                    b.HasIndex("ToCharacterId");

                    b.HasIndex("GroupId", "Status");

                    b.ToTable("ownership_transfers", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.QuotaRow", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "CharacterId", "Kind", "PeriodStart");

                    b.ToTable("quota_usage", null, t =>
                        {
                            t.HasCheckConstraint("ck_quota_usage", "\"Used\" >= 0 AND \"Used\" <= \"Limit\"");
                        });
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccessHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedProviderRefresh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RefreshExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccessHash")
                        .IsUnique();

                    b.HasIndex("RefreshHash")
                        .IsUnique();

                    b.HasIndex("CharacterId", "CreatedAt");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.UsedRefreshRow", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextRefreshHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionId");

                    b.ToTable("used_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.CategoryRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.DefinitionRevisionRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CategoryRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.DefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.DefinitionRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.GroupRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.MediaAssetRow", null)
                        .WithMany()
                        .HasForeignKey("Id", "CurrencyIconAssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.HoldingRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CategoryRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.MembershipRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.LetterRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "LetterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.DefinitionRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "DefinitionId", "DefinitionRevision")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.InvitationRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.LetterRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("AuthorCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CategoryRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.MediaAssetRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.MembershipRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.OwnershipRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("FromCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.GroupRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("ToCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.QuotaRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.MembershipRow", null)
                        .WithMany()
                        .HasForeignKey("GroupId", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AmorRP.Server.Infrastructure.Persistence.UsedRefreshRow", b =>
                {
                    b.HasOne("AmorRP.Server.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
